image: $CI_REGISTRY_IMAGE:cpu-basic-test

variables:
    OTB_BUILD: /src/otb/build/OTB/build  # Local OTB build directory
    OTBTF_SRC: /src/otbtf  # Local OTBTF source directory
    OTB_TEST_DIR: $OTB_BUILD/Testing/Temporary  # OTB testing directory
    ARTIFACT_TEST_DIR: $CI_PROJECT_DIR/testing
    CRC_BOOK_TMP: /tmp/crc_book_tests_tmp

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'develop'   # Execute jobs when a new commit is pushed to develop branch
    
stages:
  - Build
  - Static Analysis
  - Test
  - Applications Test

cpu-basic-test image:
  stage: Build
  allow_failure: false
  tags: [godzilla]
  image: docker/compose:latest
  services:
    - name: docker:dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  timeout: 10 hours
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ||
    - docker pull $CI_REGISTRY_IMAGE:cpu-basic-test || 
    - >
      docker build
      --pull
      --network="host"
      --cache-from $CI_REGISTRY_IMAGE:cpu-basic-test
      --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      --build-arg OTBTESTS="true"
      --build-arg KEEP_OTB_SRC="true"
      --build-arg BZL_CONFIGS=""
      --build-arg BASE_IMG="ubuntu:20.04"
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
#    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:cpu-basic-test
#    - docker push $CI_REGISTRY_IMAGE:cpu-basic-test

.static_analysis_base:
  stage: Static Analysis
  allow_failure: true

flake8:
  extends: .static_analysis_base
  script:
    - sudo apt update && sudo apt install flake8 -y
    - python -m flake8 --max-line-length=120 $OTBTF_SRC/python

pylint:
  extends: .static_analysis_base
  script:
    - sudo apt update && sudo apt install pylint -y
    - pylint --disable=too-many-nested-blocks,too-many-locals,too-many-statements,too-few-public-methods,too-many-instance-attributes,too-many-arguments --ignored-modules=tensorflow --max-line-length=120 --logging-format-style=new $OTBTF_SRC/python

codespell:
  extends: .static_analysis_base
  script:
    - sudo pip install codespell && codespell
    
cppcheck:
  extends: .static_analysis_base
  script:
    - sudo apt update && sudo apt install cppcheck -y
    - cd $OTBTF_SRC/ && cppcheck --enable=all --error-exitcode=1 -I include/ --suppress=missingInclude --suppress=unusedFunction .

.tests_base:
  artifacts:
    paths:
      - $ARTIFACT_TEST_DIR/*.*
    expire_in: 1 week
    when: on_failure

ctest:
  extends: .tests_base
  stage: Test
  script:
    - cd $OTB_BUILD/ && sudo ctest -L OTBTensorflow  # Run ctest
  after_script:
    - cp -r $OTB_TEST_DIR $ARTIFACT_TEST_DIR

.applications_test_base:
  extends: .tests_base
  stage: Applications Test
  rules:
      # Only for MR targeting 'develop' and 'master' branches because applications tests are slow
    - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'
    - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
  before_script:
    - pip3 install pytest pytest-cov pytest-order
    - mkdir -p $ARTIFACT_TEST_DIR
    - cd $CI_PROJECT_DIR

crc_book:
  extends: .applications_test_base
  script:
    - mkdir -p $CRC_BOOK_TMP
    - TMPDIR=$CRC_BOOK_TMP DATADIR=$CI_PROJECT_DIR/test/data python -m pytest --junitxml=$CI_PROJECT_DIR/report_tutorial.xml $OTBTF_SRC/test/tutorial_unittest.py
  after_script:
    - cp $CRC_BOOK_TMP/*.* $ARTIFACT_TEST_DIR/
    
sr4rs:
  extends: .applications_test_base
  script:
    - wget -O sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
      https://nextcloud.inrae.fr/s/EZL2JN7SZyDK8Cf/download/sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
    - unzip -o sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
    - wget -O sr4rs_data.zip https://nextcloud.inrae.fr/s/kDms9JrRMQE2Q5z/download
    - unzip -o sr4rs_data.zip
    - rm -rf sr4rs
    - git clone https://github.com/remicres/sr4rs.git
    - export PYTHONPATH=$PYTHONPATH:$PWD/sr4rs
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_sr4rs.xml $OTBTF_SRC/test/sr4rs_unittest.py
