image: gitlab-registry.irstea.fr/remi.cresson/otbtf:2.4-cpu-basic-testing


workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch
    
stages:
  - Test

before_script:
#  - sudo apt update && sudo apt install pylint flake8 cppcheck -y
#  - sudo rm -rf /src/otbtf && sudo ln -s $PWD /src/otbtf && cd /src/otb/build/OTB/build && sudo make install -j4
#  - sudo mkdir -p /src/otb/build/OTB/build/Testing/Temporary && sudo ln -s /src/otb/build/OTB/build/Testing/Temporary testing

ctest:
  stage: Test
  script:
    - sudo touch /src/otb/build/OTB/build/Testing/Temporary/fichier.tif
    - blabla fail
#    - sudo ctest -L OTBTensorflow -V ; cp -r /src/otb/build/OTB/build/Testing/Temporary/*.tif $CI_PROJECT_DIR/testing/
  after_script:
    - cp -r /src/otb/build/OTB/build/Testing/Temporary $CI_PROJECT_DIR/testing
    - ls .
    - ls $CI_PROJECT_DIR
    - ls testing
    - ls $CI_PROJECT_DIR/testing
  artifacts:
    when: on_failure
    paths:
      - testing/*.*
    expire_in: 1 week
