image: gitlab-registry.irstea.fr/remi.cresson/otbtf:2.4-cpu-basic-testing

variables:
  OTB_BUILD: /src/otb/build/OTB/build
  OTBTF_SRC: /src/otbtf

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'develop'   # Execute jobs when a new commit is pushed to develop branch
    
stages:
  - Static Analysis
  - Test

before_script:
    # Install packages for static analysis
  - sudo apt update && sudo apt install pylint flake8 cppcheck -y
    # Replace otbtf source with this git repository tested branch
  - sudo rm -rf $OTBTF_SRC && sudo ln -s $PWD $OTBTF_SRC 
    # Re-build OTB with the new OTBTF sources
  - cd $OTB_BUILD && sudo make install -j$(nproc --all)
    # Empty testing temporary folder (old generated files here)
  - sudo rm -rf $OTB_BUILD/Testing/Temporary/*

flake8:
  stage: Static Analysis
  allow_failure: true
  script:
    - python -m flake8 --max-line-length=120 $OTBTF_SRC/python
    
pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pylint --disable=too-many-nested-blocks,too-many-locals,too-many-statements,too-few-public-methods,too-many-instance-attributes,too-many-arguments --ignored-modules=tensorflow --max-line-length=120 $OTBTF_SRC/python
    
cppcheck:
  stage: Static Analysis
  allow_failure: true
  script:
    - cppcheck --enable=all --error-exitcode=1 $OTBTF_SRC/

ctest:
  stage: Test
  script:
    - cd $OTB_BUILD/ && sudo ctest -L OTBTensorflow -V
  after_script:
    - cp -r $OTB_BUILD/Testing/Temporary $CI_PROJECT_DIR/testing
  artifacts:
    when: on_failure
    paths:
      - testing/*.*
    expire_in: 1 week

