image: gitlab-registry.irstea.fr/remi.cresson/otbtf:2.4-cpu-basic-testing

variables:
  OTBTF_SRC_DIR: /src/otbtf
  OTB_BUILD_DIR: /src/otb/build/OTB/build
  OTB_TESTS_DIR: $OTB_BUILD_DIR/Testing/Temporary
  ARTIFACTS_DIR: testing

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch
    
stages:
  - Test

before_script:
  - sudo apt update && sudo apt install pylint flake8 cppcheck -y
  - sudo rm -rf $OTBTF_SRC_DIR && sudo ln -s $PWD $OTBTF_SRC_DIR && cd $OTB_BUILD_DIR && sudo make install -j4

ctest:
  stage: Test
  before_script:
    - sudo rm -rf $OTB_TESTS_DIR/*
  script:
    - sudo ctest -L OTBTensorflow -V
  after_script:
    - cp -r $OTB_TESTS_DIR/* $CI_PROJECT_DIR/$ARTIFACTS_DIR
  artifacts:
    when: on_failure
    paths:
      - $ARTIFACTS_DIR/*.*
    expire_in: 1 week
