image: gitlab-registry.irstea.fr/remi.cresson/otbtf:2.4-cpu-basic-testing


workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch
    
stages:
  - Static Analysis
  - Test

before_script:
  - python --version
  - sudo apt update && sudo apt install pylint flake8 cppcheck -y
  - sudo rm -rf /src/otbtf && sudo ln -s $PWD /src/otbtf && cd /src/otb/build/OTB/build && sudo make install -j4 && cd /src/otbtf
  
flake8:
  stage: Static Analysis
  script:
    - python -m flake8 --max-line-length=120 $PWD/python
    
pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pylint --disable=too-many-nested-blocks,too-many-locals,too-many-statements,too-few-public-methods,too-many-instance-attributes,too-many-arguments --ignored-modules=tensorflow --max-line-length=120 $PWD/python
    
cppcheck:
  stage: Static Analysis
  allow_failure: true
  script:
    - cppcheck --enable=all --error-exitcode=1 /src/otbtf
    
ctest:
  stage: Test
  script:
    - cd /src/otb/build/OTB/build && sudo ctest -L OTBTensorflow -V

